from __future__ import annotations

import re
from difflib import SequenceMatcher
from functools import lru_cache
from typing import Optional


_SKILL_ALIASES: dict[str, str] = {
    "prompt engineering": "Prompt Engineering",
    "prompt eng": "Prompt Engineering",
    "rag": "RAG (Retrieval-Augmented Generation)",
    "retrieval augmented generation": "RAG (Retrieval-Augmented Generation)",
    "cuda": "CUDA",
    "cuda programming": "CUDA",
    "terraform": "Terraform",
    "pulumi": "Pulumi",
    "iac": "Infrastructure as Code",
    "infrastructure as code": "Infrastructure as Code",
    "grafana": "Grafana",
    "prometheus": "Prometheus",
    "datadog": "Datadog",
    "newrelic": "New Relic",
    "new relic": "New Relic",
    "celery": "Celery",
    "rq": "Redis Queue",
    "redis queue": "Redis Queue",
    "apache kafka": "Kafka",
    "apache spark": "Spark",
    "apache flink": "Flink",
    "apache airflow": "Airflow",
    "assembly": "Assembly Language",
    "assembly language": "Assembly Language",
    "vhdl": "VHDL",
    "fpga": "FPGA",
    "cobol": "COBOL",
    "fortran": "Fortran",
    "unity3d": "Unity",
    "unity 3d": "Unity",
    "unreal engine": "Unreal Engine",
    "ue4": "Unreal Engine",
    "ue5": "Unreal Engine",
    "game development": "Game Development",
    "autocad": "AutoCAD",
    "solidworks": "SolidWorks",
    "cad": "CAD",
    "matlab": "MATLAB",
    "simulink": "Simulink",
    "solidity": "Solidity",
    "web3": "Web3",
    "blockchain": "Blockchain",
    "smart contracts": "Smart Contracts",
    "ethereum": "Ethereum",
    "dbt": "dbt",
    "great expectations": "Great Expectations",
    "apache beam": "Apache Beam",
    "databricks": "Databricks",
    "snowflake": "Snowflake",
    "bigquery": "BigQuery",
    "redshift": "Amazon Redshift",
    "amazon redshift": "Amazon Redshift",
    "looker": "Looker",
    "metabase": "Metabase",
    "superset": "Apache Superset",
    "apache superset": "Apache Superset",
    "flask-restful": "Flask",
    "flask restful": "Flask",
    "fastapi framework": "FastAPI",
    "tortoise orm": "Tortoise ORM",
    "sqlalchemy": "SQLAlchemy",
    "alembic": "Alembic",
    "pydantic": "Pydantic",
    "celery beat": "Celery",
    "gunicorn": "Gunicorn",
    "nginx": "Nginx",
    "apache httpd": "Apache HTTP Server",
    "traefik": "Traefik",
    "istio": "Istio",
    "envoy": "Envoy",
    "consul": "Consul",
    "vault": "HashiCorp Vault",
    "hashicorp vault": "HashiCorp Vault",
    "ansible": "Ansible",
    "puppet": "Puppet",
    "chef": "Chef",
    "saltstack": "SaltStack",
    "packer": "Packer",
    "vagrant": "Vagrant",
    "elasticsearch": "Elasticsearch",
    "opensearch": "OpenSearch",
    "kibana": "Kibana",
    "logstash": "Logstash",
    "elk stack": "ELK Stack",
    "elastic stack": "ELK Stack",
    "fluentd": "Fluentd",
    "fluentbit": "Fluent Bit",
    "fluent bit": "Fluent Bit",
    "jaeger": "Jaeger",
    "zipkin": "Zipkin",
    "opentelemetry": "OpenTelemetry",
    "open telemetry": "OpenTelemetry",
    "grpc": "gRPC",
    "graphql api": "GraphQL",
    "rest api": "REST API",
    "restful api": "REST API",
    "websockets": "WebSockets",
    "websocket": "WebSockets",
    "socket.io": "Socket.IO",
    "oauth2": "OAuth 2.0",
    "oauth 2.0": "OAuth 2.0",
    "jwt": "JWT",
    "json web token": "JWT",
    "json web tokens": "JWT",
    "openid connect": "OpenID Connect",
    "oidc": "OpenID Connect",
    "saml": "SAML",
    "ldap": "LDAP",
    "active directory": "Active Directory",
    "azure ad": "Azure Active Directory",
    "aws iam": "AWS IAM",
    "aws lambda": "AWS Lambda",
    "aws ec2": "AWS EC2",
    "aws s3": "AWS S3",
    "aws rds": "AWS RDS",
    "aws eks": "AWS EKS",
    "aws ecs": "AWS ECS",
    "aws sqs": "AWS SQS",
    "aws sns": "AWS SNS",
    "aws cloudformation": "AWS CloudFormation",
    "aws cdk": "AWS CDK",
    "google cloud": "GCP",
    "google cloud platform": "GCP",
    "gke": "Google Kubernetes Engine",
    "google kubernetes engine": "Google Kubernetes Engine",
    "cloud run": "Google Cloud Run",
    "azure functions": "Azure Functions",
    "azure aks": "Azure AKS",
    "azure devops": "Azure DevOps",
    "github actions": "GitHub Actions",
    "gitlab ci": "GitLab CI/CD",
    "gitlab ci/cd": "GitLab CI/CD",
    "circle ci": "CircleCI",
    "circleci": "CircleCI",
    "travis ci": "Travis CI",
    "jenkins pipeline": "Jenkins",
    "argocd": "ArgoCD",
    "flux cd": "Flux",
    "fluxcd": "Flux",
    "helm charts": "Helm",
    "helm chart": "Helm",
    "kustomize": "Kustomize",
    "vitejs": "Vite",
    "vite.js": "Vite",
    "nextjs": "Next.js",
    "next.js": "Next.js",
    "nuxtjs": "Nuxt.js",
    "nuxt.js": "Nuxt.js",
    "gatsby.js": "Gatsby",
    "gatsbyjs": "Gatsby",
    "remix": "Remix",
    "astro": "Astro",
    "sveltekit": "SvelteKit",
    "svelte kit": "SvelteKit",
    "electron": "Electron",
    "electronjs": "Electron",
    "tauri": "Tauri",
    "react native": "React Native",
    "expo": "Expo",
    "flutter framework": "Flutter",
    "dart": "Dart",
    "swiftui": "SwiftUI",
    "uikit": "UIKit",
    "jetpack compose": "Jetpack Compose",
    "android sdk": "Android SDK",
    "ios sdk": "iOS SDK",
    "xcode": "Xcode",
    "android studio": "Android Studio",
    "hugging face": "Hugging Face",
    "transformers": "Hugging Face Transformers",
    "huggingface": "Hugging Face",
    "langchain": "LangChain",
    "llama": "LLaMA",
    "llama2": "LLaMA 2",
    "llama 2": "LLaMA 2",
    "gpt-4": "GPT-4",
    "gpt4": "GPT-4",
    "chatgpt": "ChatGPT",
    "openai api": "OpenAI API",
    "stable diffusion": "Stable Diffusion",
    "midjourney": "Midjourney",
    "vector database": "Vector Database",
    "vector db": "Vector Database",
    "pinecone": "Pinecone",
    "weaviate": "Weaviate",
    "chroma": "ChromaDB",
    "chromadb": "ChromaDB",
    "qdrant": "Qdrant",
    "faiss": "FAISS",
    "annoy": "Annoy",
    "milvus": "Milvus",
    "sentence transformers": "Sentence Transformers",
    "sentence-transformers": "Sentence Transformers",
    "spacy": "spaCy",
    "nltk": "NLTK",
    "gensim": "Gensim",
    "opencv": "OpenCV",
    "pillow": "Pillow",
    "imageio": "imageio",
    "albumentations": "Albumentations",
    "yolo": "YOLO",
    "detectron": "Detectron2",
    "detectron2": "Detectron2",
    "mmdet": "MMDetection",
    "mmdetection": "MMDetection",
    "timm": "timm",
    "wandb": "Weights & Biases",
    "weights and biases": "Weights & Biases",
    "weights & biases": "Weights & Biases",
    "mlflow": "MLflow",
    "dvc": "DVC",
    "bentoml": "BentoML",
    "torchserve": "TorchServe",
    "triton": "NVIDIA Triton",
    "nvidia triton": "NVIDIA Triton",
    "onnx": "ONNX",
    "tensorrt": "TensorRT",
    "openvino": "OpenVINO",
    "ray": "Ray",
    "dask": "Dask",
    "prefect": "Prefect",
    "luigi": "Luigi",
    "great expectations": "Great Expectations",
    "feast": "Feast",
    "tecton": "Tecton",
    "vertex ai": "Vertex AI",
    "sagemaker": "Amazon SageMaker",
    "amazon sagemaker": "Amazon SageMaker",
    "azure ml": "Azure Machine Learning",
    "azure machine learning": "Azure Machine Learning",
    "power automate": "Power Automate",
    "power apps": "Power Apps",
    "sharepoint": "SharePoint",
    "ms sharepoint": "SharePoint",
    "ms teams": "Microsoft Teams",
    "microsoft teams": "Microsoft Teams",
    "jira software": "Jira",
    "confluence wiki": "Confluence",
    "notion": "Notion",
    "airtable": "Airtable",
    "monday.com": "Monday.com",
    "asana": "Asana",
    "trello": "Trello",
    "linear": "Linear",
    "clickup": "ClickUp",
    "postman api": "Postman",
    "insomnia": "Insomnia",
    "swagger ui": "Swagger",
    "openapi": "OpenAPI",
    "openapi specification": "OpenAPI",
    "protobuf": "Protocol Buffers",
    "protocol buffers": "Protocol Buffers",
    "avro": "Apache Avro",
    "apache avro": "Apache Avro",
    "parquet": "Apache Parquet",
    "apache parquet": "Apache Parquet",
    "delta lake": "Delta Lake",
    "apache iceberg": "Apache Iceberg",
    "iceberg": "Apache Iceberg",
    "hudi": "Apache Hudi",
    "apache hudi": "Apache Hudi",
    "presto": "Presto",
    "trino": "Trino",
    "clickhouse": "ClickHouse",
    "apache cassandra": "Cassandra",
    "cassandra db": "Cassandra",
    "couchdb": "CouchDB",
    "apache couchdb": "CouchDB",
    "neo4j": "Neo4j",
    "graph database": "Graph Database",
    "graph db": "Graph Database",
    "influxdb": "InfluxDB",
    "timescaledb": "TimescaleDB",
    "cockroachdb": "CockroachDB",
    "planetscale": "PlanetScale",
    "supabase": "Supabase",
    "firebase realtime database": "Firebase",
    "firestore": "Firestore",
    "realm": "Realm",
    "sqlite3": "SQLite",
    "mysql 8": "MySQL",
    "postgres": "PostgreSQL",
    "pg": "PostgreSQL",
    "ms sql": "SQL Server",
    "microsoft sql server": "SQL Server",
    "mssql": "SQL Server",
    "oracle db": "Oracle Database",
    "oracle database": "Oracle Database",
    "pl/sql": "PL/SQL",
    "t-sql": "T-SQL",
    "transact-sql": "T-SQL",
    "python3": "Python",
    "python 3": "Python",
    "cpython": "Python",
    "golang": "Go",
    "go lang": "Go",
    "typescript 4": "TypeScript",
    "ts": "TypeScript",
    "javascript es6": "JavaScript",
    "es6": "JavaScript",
    "vanilla js": "JavaScript",
    "cpp": "C++",
    "c plus plus": "C++",
    "csharp": "C#",
    "c sharp": "C#",
    "fsharp": "F#",
    "f sharp": "F#",
    "vb.net": "Visual Basic .NET",
    "visual basic": "Visual Basic .NET",
    "objective-c": "Objective-C",
    "objc": "Objective-C",
    "haskell": "Haskell",
    "erlang": "Erlang",
    "elixir": "Elixir",
    "clojure": "Clojure",
    "lisp": "Lisp",
    "scheme": "Scheme",
    "prolog": "Prolog",
    "r language": "R",
    "r programming": "R",
    "rlang": "R",
    "julia": "Julia",
    "nim": "Nim",
    "zig": "Zig",
    "crystal": "Crystal",
    "d lang": "D",
    "dlang": "D",
    "lua": "Lua",
    "groovy": "Groovy",
    "kotlin multiplatform": "Kotlin",
    "kmm": "Kotlin Multiplatform",
    "kotlin multiplatform mobile": "Kotlin Multiplatform",
    "spring framework": "Spring",
    "spring boot 3": "Spring Boot",
    "micronaut": "Micronaut",
    "quarkus": "Quarkus",
    "ktor": "Ktor",
    "express.js": "Express",
    "expressjs": "Express",
    "koa.js": "Koa",
    "koajs": "Koa",
    "hapi.js": "Hapi",
    "fastify": "Fastify",
    "nestjs": "NestJS",
    "nest.js": "NestJS",
    "adonis.js": "AdonisJS",
    "adonisjs": "AdonisJS",
    "laravel framework": "Laravel",
    "symfony framework": "Symfony",
    "codeigniter": "CodeIgniter",
    "rails": "Ruby on Rails",
    "ruby on rails": "Ruby on Rails",
    "sinatra": "Sinatra",
    "asp.net": "ASP.NET",
    "asp.net core": "ASP.NET Core",
    ".net core": ".NET Core",
    "dotnet": ".NET",
    "blazor": "Blazor",
    "xamarin": "Xamarin",
    "maui": ".NET MAUI",
    ".net maui": ".NET MAUI",
    "wpf": "WPF",
    "winforms": "WinForms",
    "uwp": "UWP",
    "pandas dataframe": "Pandas",
    "numpy array": "NumPy",
    "matplotlib pyplot": "Matplotlib",
    "seaborn visualization": "Seaborn",
    "plotly express": "Plotly",
    "bokeh": "Bokeh",
    "altair": "Altair",
    "d3.js": "D3.js",
    "d3js": "D3.js",
    "three.js": "Three.js",
    "threejs": "Three.js",
    "webgl": "WebGL",
    "babylonjs": "Babylon.js",
    "babylon.js": "Babylon.js",
    "ag grid": "AG Grid",
    "ag-grid": "AG Grid",
    "tanstack query": "TanStack Query",
    "react query": "TanStack Query",
    "zustand": "Zustand",
    "jotai": "Jotai",
    "recoil": "Recoil",
    "mobx": "MobX",
    "ngrx": "NgRx",
    "vuex": "Vuex",
    "pinia": "Pinia",
    "tailwindcss": "Tailwind CSS",
    "tailwind css": "Tailwind CSS",
    "bootstrap 5": "Bootstrap",
    "material ui": "Material UI",
    "mui": "Material UI",
    "ant design": "Ant Design",
    "antd": "Ant Design",
    "chakra ui": "Chakra UI",
    "shadcn": "shadcn/ui",
    "shadcn/ui": "shadcn/ui",
    "headless ui": "Headless UI",
    "radix ui": "Radix UI",
    "styled components": "Styled Components",
    "emotion": "Emotion",
    "css modules": "CSS Modules",
    "sass": "Sass",
    "scss": "Sass",
    "less": "Less",
    "storybook": "Storybook",
    "cypress": "Cypress",
    "playwright": "Playwright",
    "selenium webdriver": "Selenium",
    "puppeteer": "Puppeteer",
    "jest testing": "Jest",
    "vitest": "Vitest",
    "mocha": "Mocha",
    "chai": "Chai",
    "pytest framework": "pytest",
    "unittest": "unittest",
    "testng": "TestNG",
    "junit 5": "JUnit",
    "junit5": "JUnit",
    "mockito": "Mockito",
    "k6": "k6",
    "locust": "Locust",
    "jmeter": "JMeter",
    "gatling": "Gatling",
    "sonarqube": "SonarQube",
    "sonar": "SonarQube",
    "fortify": "Fortify",
    "veracode": "Veracode",
    "snyk": "Snyk",
    "owasp": "OWASP",
    "penetration testing": "Penetration Testing",
    "pen testing": "Penetration Testing",
    "ethical hacking": "Ethical Hacking",
    "burp suite": "Burp Suite",
    "metasploit": "Metasploit",
    "wireshark": "Wireshark",
    "nmap": "Nmap",
    "kali linux": "Kali Linux",
    "cyber security": "Cybersecurity",
    "cybersecurity": "Cybersecurity",
    "information security": "Information Security",
    "infosec": "Information Security",
    "devsecops": "DevSecOps",
    "soc": "SOC",
    "siem": "SIEM",
    "splunk": "Splunk",
    "qradar": "IBM QRadar",
    "ibm qradar": "IBM QRadar",
    "pmp": "PMP",
    "prince2": "PRINCE2",
    "safe": "SAFe",
    "scaled agile": "SAFe",
    "kanban": "Kanban",
    "six sigma": "Six Sigma",
    "lean": "Lean",
    "okr": "OKRs",
    "okrs": "OKRs",
    "product management": "Product Management",
    "product strategy": "Product Strategy",
    "user research": "User Research",
    "ux research": "UX Research",
    "usability testing": "Usability Testing",
    "a/b testing": "A/B Testing",
    "ab testing": "A/B Testing",
    "growth hacking": "Growth Hacking",
    "seo": "SEO",
    "sem": "SEM",
    "google analytics": "Google Analytics",
    "ga4": "Google Analytics 4",
    "mixpanel": "Mixpanel",
    "amplitude": "Amplitude",
    "segment": "Segment",
    "hubspot": "HubSpot",
    "salesforce crm": "Salesforce",
    "zendesk": "Zendesk",
    "intercom": "Intercom",
    "twilio": "Twilio",
    "sendgrid": "SendGrid",
    "mailchimp": "Mailchimp",
    "stripe api": "Stripe",
    "razorpay api": "Razorpay",
    "payment gateway": "Payment Gateway",
    "technical writing": "Technical Writing",
    "documentation": "Documentation",
    "api documentation": "API Documentation",
    "system design": "System Design",
    "low level design": "Low-Level Design",
    "lld": "Low-Level Design",
    "high level design": "High-Level Design",
    "hld": "High-Level Design",
    "data structures": "Data Structures",
    "data structures and algorithms": "DSA",
    "dsa": "DSA",
    "algorithms": "Algorithms",
    "dynamic programming": "Dynamic Programming",
    "dp": "Dynamic Programming",
    "operating systems": "Operating Systems",
    "os": "Operating Systems",
    "computer networks": "Computer Networks",
    "networking": "Networking",
    "tcp/ip": "TCP/IP",
    "http/2": "HTTP/2",
    "http2": "HTTP/2",
    "distributed systems": "Distributed Systems",
    "microservices architecture": "Microservices",
    "event driven architecture": "Event-Driven Architecture",
    "event-driven": "Event-Driven Architecture",
    "cqrs": "CQRS",
    "event sourcing": "Event Sourcing",
    "domain driven design": "DDD",
    "ddd": "DDD",
    "solid principles": "SOLID",
    "solid": "SOLID",
    "design patterns": "Design Patterns",
    "clean architecture": "Clean Architecture",
    "test driven development": "TDD",
    "tdd": "TDD",
    "behavior driven development": "BDD",
    "bdd": "BDD",
    "ci/cd pipeline": "CI/CD",
    "continuous integration": "CI/CD",
    "continuous deployment": "CI/CD",
    "devops practices": "DevOps",
    "site reliability engineering": "SRE",
    "sre": "SRE",
    "chaos engineering": "Chaos Engineering",
    "observability": "Observability",
    "load balancing": "Load Balancing",
    "caching": "Caching",
    "cdn": "CDN",
    "content delivery network": "CDN",
    "serverless": "Serverless",
    "serverless architecture": "Serverless",
    "edge computing": "Edge Computing",
    "multi-tenancy": "Multi-tenancy",
    "saas": "SaaS",
    "paas": "PaaS",
    "iaas": "IaaS",
}

_NORMALIZED_CACHE: dict[str, str] = {}


def _normalize_for_lookup(text: str) -> str:
    text = text.lower().strip()
    text = re.sub(r"[^\w\s./#+@-]", " ", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()


@lru_cache(maxsize=2048)
def _cached_lookup(normalized: str) -> Optional[str]:
    if normalized in _SKILL_ALIASES:
        return _SKILL_ALIASES[normalized]

    for k, v in _SKILL_ALIASES.items():
        if k in normalized or normalized in k:
            if abs(len(k) - len(normalized)) <= 5:
                ratio = SequenceMatcher(None, normalized, k).ratio()
                if ratio >= 0.85:
                    return v

    return None


def match_skill(raw: str) -> Optional[str]:
    if not raw or not raw.strip():
        return None

    normalized = _normalize_for_lookup(raw)
    if not normalized:
        return None

    exact = _SKILL_ALIASES.get(normalized)
    if exact:
        return exact

    cached = _cached_lookup(normalized)
    return cached


def normalize_unknown_skill(raw: str) -> str:
    matched = match_skill(raw)
    if matched:
        return matched

    cleaned = raw.strip()
    if cleaned.isupper() and len(cleaned) <= 8:
        return cleaned

    if all(c.isupper() or c in "/.#+@-0123456789 " for c in cleaned):
        return cleaned

    words = cleaned.split()
    if len(words) == 1:
        return cleaned[0].upper() + cleaned[1:] if cleaned else cleaned

    return " ".join(
        w[0].upper() + w[1:] if not w.isupper() else w
        for w in words
    )


def bulk_match_skills(raw_skills: list[str]) -> list[str]:
    result: list[str] = []
    seen: set[str] = set()

    for raw in raw_skills:
        if not raw or not raw.strip():
            continue
        canonical = normalize_unknown_skill(raw)
        key = canonical.lower()
        if key not in seen:
            seen.add(key)
            result.append(canonical)

    return result
